import Head from 'next/head';
import Link from 'next/link';
import { Fragment } from 'react';

//#region Styled Components

//#endregion

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icso" />
      </Head>
      <div>
        this is index page
        <Link href={'/login'}>
          <div>로그인 페이지로 이동</div>
        </Link>
      </div>
    </Fragment>
  );
}
